# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-05 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='granted',
            field=models.BooleanField(default=False),
        ),
    ]
