# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-05 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish', '0002_auto_20190205_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='wishes',
            field=models.ManyToManyField(related_name='userWishes', to='wish.User'),
        ),
    ]
