# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-05 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wish', '0003_auto_20190205_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='createdby',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wish', to='wish.User'),
            preserve_default=False,
        ),
    ]
