# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-05 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish', '0004_wish_createdby'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('likedBy', models.ManyToManyField(related_name='likedBy', to='wish.User')),
                ('likedWish', models.ManyToManyField(related_name='likedWish', to='wish.Wish')),
            ],
        ),
    ]
