# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-05 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish', '0006_auto_20190205_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='likedBy',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='likedWish',
        ),
        migrations.AddField(
            model_name='wish',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to='wish.User'),
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
