# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-05 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish', '0007_auto_20190205_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='wishes',
        ),
        migrations.AlterField(
            model_name='wish',
            name='likes',
            field=models.ManyToManyField(related_name='liked', to='wish.User'),
        ),
    ]
